# Generated by Django 4.0.4 on 2022-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.DeleteModel(
            name='Icecream',
        ),
    ]
